### ISSUE TITLE
Is it possible to implement an ordered protocol with tokio-rs?

### ISSUE THREAD

**Issue by adrianbrink** [tokio-rs/tokio-proto#177]
I am implementing a protocol that sends messages in order and I need to process them in order. However I can process multiple messages before I send a response.

The server can receive 3 messages from the client, process them (IN ORDER) and then send back three responses. 
Is this possible to do with tokio-rs?

**Comment by sateffen** [comment]
Short answer: Yes.

Long answer: It depends on your implementation. The documentation of [tokio-proto](https://docs.rs/tokio-proto/0.1.1/tokio_proto/) tells about pipelined protocolls:

> In a pipelined protocol, the server responds to client requests in the order they were sent. Example pipelined protocols include HTTP/1.1 and Redis. Pipelining with the max number of in-flight requests set to 1 implies that for each request, the response must be received before sending another request on the same connection.
 
so it's basically what you want.

Processing in correct order depends on your processing logic. You could setup a processing-queue, that handles each incoming request in order. Tokio does not really care about how you process stuff.

**Comment by adrianbrink** [comment]
Perfect.

One more question: I have a length-prefixed protocol. So I need to read the first byte and extract it as a number. That then tells me how many bytes to read afterwards. 

What could happen is that decode is called, I remove the first byte from the buffer, but then notice that the rest of the message isn't in the buffer yet. How do I return None and revert the state of the buffer back to the original?

**Comment by sateffen** [comment]
Just don't slice the byte of the buffer. In *decode* you'll get a buffer, where you can read the very first byte without consuming it. Your *decode* function gets a [BytesMut](https://carllerche.github.io/bytes/bytes/struct.BytesMut.html) struct, which implements a simple *get(index)* function. With that you can peek into the buffer, check the full length, and check whether *len()* is your count+1 (1 for the first byte). If your buffer contains all data, you can drain it down, if not, just return `Ok(None)` from your *decode* implementation, instead of `Ok(Some(data...))`.

**Comment by adrianbrink** [comment]
[This](https://github.com/tendermint/rust-abci/blob/feature/socket_support/src/socket_server.rs#L22) is my decode method.

The thing is that I have to check the first byte, which determines the length of the amount of next bytes to read, which then determines the length of the actual message. And only if I have enough bytes in the buffer to read the entire message should I proceed.

Is there something like `get` but for ranges?
