### ISSUE TITLE
`TcpClient` leaks connection

### ISSUE THREAD

**Issue by jvff** [tokio-rs/tokio-proto#194]
I don't know if this is an expected behavior, but it seems that a TcpClient somehow leaks its internal connection (a TcpStream instance?) into the tokio_core::reactor::Core it's running on.

I created an [example test case][1] that has two tests. One test forces the Core instance to drop before the test asserts that the connection is closed (somewhat indirectly, by checking if a dummy server thread has finished). The other lets the Core instance live beyond the assertion, so it's only dropped in the end of the test. The first test succeeds, while the second fails.

[1]: https://github.com/jvff/possible_tokio-proto_tcpclient_connection_leak

**Comment by AndrewBrinker** [comment]
Can you share the tests?

**Comment by jvff** [comment]
I updated the post, sorry. I copied it from an issue I opened incorrectly on Tokio, but I forgot to copy the link.

The repository with the test case is: https://github.com/jvff/possible_tokio-proto_tcpclient_connection_leak

**Comment by cramertj** [comment]
I've been trying to dig into this a bit, since I seem to be experiencing similar leaks when using hyper in Fuchsia. What's happening is that the TcpStream client isn't being closed, so the server sits open waiting for more messages. The `connection` you have isn't actually a `TcpStream`, it's a `ClientProxy<Message<Vec<u8>, Empty<(), io::Error>>, Message<std::vec::Vec<u8>, Body<(), io::Error>>, io::Error>`. Note that there's no `TcpStream` in that type signature or anything else telling it the type of the transport. That's because it's just a [ClientProxy](https://github.com/tokio-rs/tokio-proto/blob/master/src/util/client_proxy.rs#L23) with a channel that [sends pairs of (request, response_channel)](https://github.com/tokio-rs/tokio-proto/blob/master/src/util/client_proxy.rs#L76). The actual transport mechanism is spawned onto the executor as part of the `Dispatch` struct [here](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/client.rs#L68). The dispatch struct is placed inside a [Pipeline](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L22), which is itself a [Future](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L358) which will be dropped by tokio-core's `Core` (the executor in this case) when it resolves to `Async::Ready` (just like any other future. In this case, that only happens when [`is_done` is true](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L391) ([`self.run` is false](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L110) and all in-flight messages have completed). AFAICT, `self.run` only gets set to false when [process_out_frame](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L139) is called with `None`, which weirdly will only ever happen if `self.dispatch.get_mut().inner.transport().poll()` returns `Async::Ready(None)`. This does _not_ happen if merely the dispatch channel has been closed-- in that case, [this code will receive an `Async::Ready(None)` from polling the `Dispatch` and `break`](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L252), but it doesn't actually close anything until _transport_ returns that it is dead.

Sorry for the long message. This was my first time reading through tokio-proto and it's... an experience. Extra credit goes to [this type](https://tokio-rs.github.io/tokio-proto/src/tokio_proto/simple/pipeline/client.rs.html#86).

In my confusion, I could be mistaken, but my understanding is that [this case here](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L252) should be changed to set `self.run = false;` so that the `Pipeline` will complete [once the output stream is flushed and there are no more requests in flight](https://github.com/tokio-rs/tokio-proto/blob/master/src/streaming/pipeline/advanced.rs#L110).

**Comment by cramertj** [comment]
@jvff I've opened a https://github.com/tokio-rs/tokio-proto/pull/195 which fixes this issue. @jvff-- I hope you don't mind-- I also included your test above as a regression test for this issue. Let me know if you don't want it up and I'll replace it with something else.

**Comment by leodasvacas** [comment]
Is #181 related?

**Comment by jvff** [comment]
@leodasvacas , I placed the same test code used in #181 into the test case in #195, and it seems to be fixed by that pull request. Therefore I believe they are the same.
