### ISSUE TITLE
unimplemented hit in pipeline

### ISSUE THREAD

**Issue by daiheitan** [tokio-rs/tokio-proto#71]
Here's a gist for a general concept of the problem: https://gist.github.com/daiheitan/35a089e2065f96a9c985c27e57f286dd

Hitting: https://github.com/tokio-rs/tokio-proto/blob/overhaul/src/pipeline/pipeline.rs#L270

**Comment by quininer** [comment]
same problem. https://github.com/Tyzzer/honeydipper/blob/master/examples/client.rs#L39

**Comment by daiheitan** [comment]
There seems to be a dirty and quick fix of this problem: replace `unimplemented` with:

```
try!(self.dispatch.transport().write(Frame::Done));
self.in_body = None;
```

**Comment by seanmonstar** [comment]
This happens on master, at https://github.com/tokio-rs/tokio-proto/blob/cd760cc96ed380cc6b4dfbcddeac6e60764c886b/src/streaming/pipeline/advanced.rs#L278

**Comment by hjr3** [comment]
Prior to the revamp, I would hit this when my write buffer was full and I was not actually writing the message out. It was a bug in my `poll_write()` implementation.

**Comment by seanmonstar** [comment]
This happens when you drop a ClientProxy, which is a very normal thing to do, such as when the server closes the socket.

**Comment by ashleysommer** [comment]
I'm hitting this on master too.
Looks like all client implementations using the refactored code will hit this.

**Comment by ashleysommer** [comment]
Thanks for the fix. I hope it gets pulled in soon.

I went digging deeper to see what was actually causing this (simply to aide my understanding of the tokio-proto->tokio-core->futures-rs architecture), because I couldn't work out why the pipeline would be recieving an `Async::Ready(None)` from the `ClientProxy`. The `requests` (`Receiver`) implementation in the `ClientProxy` looks like it shouldn't be able to return a `Async::Ready(None)`.

I dug further, to find that the `Receiver` is based on an mpsc FIFO queue from `futures-rs`. Checking out its implementation, I found that when it is checking for new from its `message_queue`, it does one of two things. Firstly, if there is a message available, it returns it as `Ok(Async::Ready(msg))`, or if there is no messages available it will try to park the routine to wait for new messages, using `try_park`. This is where the magic happens. When trying to park, if the `ClientProxy` connection is actually closed (and no more messages will come in), it returns `Ok(Async::Ready(None))` from the `try_park` function.
This is the place in the source that the `None` comes from: https://github.com/alexcrichton/futures-rs/blob/master/src/sync/mpsc/mod.rs#L720
This then gets propagated to the `ClientProxy`, then to the Pipeline, then to the `unimplemented!()` block.

So it seems like the only way to prevent this would be to shut down the `Pipeline` before shutting down the `ClientService`, which I don't think is possible in the current implementation, all clients using `ClientService` will see this exception when shutting down the connection.

Also, while not directly related, this is also of interest:
https://github.com/alexcrichton/futures-rs/commit/b22e86ceb32f1be259fecde6c7f72a1a216e69d7

Edit: Just saw the fix was merged while I was typing this out. Thanks @carllerche
